
# SEO settings
title: ""
title2: "Jimmy Ba" # default: ""
description: "Yet another researcher's home page."
keywords: "jimmy ba, machine learning, research"
url: http://jimmylba.github.io # site url
#baseurl: "/jimmylba" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://jimmylba.github.io
disqus_shortname: "jimmylba"
twitter_username: "jimmylba"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Jimmy Ba"
  job      : "PhD student"
  bio      : "Blahh."
  thumb    : /images/author.jpg
  email    : jimmy@psi.toronto.edu
  url      : http://jimmylba.github.io
  #github   : http://github.com/heiswayi
  #twitter  : http://twitter.com/HeiswayiNrird
  #facebook : https://www.facebook.com/profile.php?id=1257583160
  #linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "en_US"
#twitter_card: "summary_large_image"
#twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
