
# SEO settings
title: ""
title2: "Jimmy Ba" # default: ""
description: "home page"
keywords: "jimmy ba, deep learning, neural networks, machine learning"
url: http://jimmylba.github.io # site url
#baseurl: "/jimmylba" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-110096440-1
repo: http://jimmylba.github.io
disqus_shortname: "jimmylba"
twitter_username: "jimmylba"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Jimmy Ba"
  job      : "Assistant Professor"
  bio      : "."
  thumb    : /images/author.jpg
  email    : jba@cs.toronto.edu
  url      : http://jimmylba.github.io
  #github   : http://github.com/jimmylba
  #twitter  : http://twitter.com/jimmylba
  #facebook : https://www.facebook.com/jimmyleiba
  #linkedin : http://linkedin.com/in/jimmylba

# social settings
og_locale: "en_US"
#twitter_card: "summary_large_image"
#twitter_site: "@jimmylba"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
